In [1]:
import numpy as np

In [12]:
my_list = [1,2,3,4,5,6]
arr = np.array(my_list)

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.shape

(6,)

In [15]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [16,17,18,91,110]


arr1 = np.array([l1,l2,l3])


In [21]:
arr1

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 16,  17,  18,  91, 110]])

In [28]:
arr1 = arr1.reshape(5,3)
arr1

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  16,  17],
       [ 18,  91, 110]])

In [29]:
arr1.shape

(5, 3)

In [38]:
arr1[1:3,1:2]

array([[5],
       [8]])

In [39]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])