In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame({'text':['people watch me','me watch me','people write comment','me write comment'],'output':[1,1,0,0]})

In [21]:
df

text  output
0       people watch me       1
1           me watch me       1
2  people write comment       0
3      me write comment       0

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [23]:
bow = cv.fit_transform(df['text'])

In [24]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'me': 1, 'write': 4, 'comment': 0}


In [25]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]


In [26]:
cv.transform(["aj kal me watch that shit people with me"]).toarray()

array([[0, 2, 1, 1, 0]], dtype=int64)